[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "php -S localhost:8001"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"

[variables]
  DB_HOST = "containers.railway.app"
  DB_NAME = "railway"
  DB_USER = "railway"
  DB_PASS = "${{RAILWAY_PRIVATE_PASSWORD}"
  JWT_SECRET = "${{RAILWAY_PRIVATE_JWT_SECRET}"
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_URL = "${{RAILWAY_PUBLIC_URL}}"
