[build]
  builder = "nixpacks"

[deploy]
  startCommand = "php -S 0.0.0.0:8001 -t ."
  healthcheckPath = "/api/health"
  healthcheckTimeout = 100
  restartPolicyType = "ON_FAILURE"
  sleepApplication = false

[variables]
  DB_HOST = "ep-young-voice-ah2904qr-pooler.c-3.us-east-1.aws.neon.tech"
  DB_NAME = "neondb"
  DB_USER = "neondb_owner"
  DB_PASS = "npg_oaUnfsOMG9e7"
  DB_PORT = "5432"
  DB_SSL = "require"
  JWT_SECRET = "your_super_secret_jwt_key_change_this_in_production"
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_URL = "${{RAILWAY_PUBLIC_URL}}"
